Shapes
mellena1/mbta-v3-go pull request #17
Opened 2019-06-06 02:15 UTC by ImmaBird

added the shapes endpoint

2019-06-06 02:16 UTC, ImmaBird commented
This PR addresses issue #13

2019-06-09 19:41 UTC, mellena1 requested changes

2019-06-09 19:41 UTC, mellena1 commented on mbta/shapes.go
> +	ShapeIncludeStop               = includeStop
should be `stops` not `stop`

2019-06-09 19:41 UTC, mellena1 commented on go.mod
> +	github.com/twpayne/go-polyline v1.0.0 // indirect
get rid of this

2019-06-09 19:41 UTC, mellena1 commented on go.sum
> +github.com/twpayne/go-polyline v1.0.0 h1:EA8HPg0MNS62R5D2E8B6zyz2TMkmkXVlQaVBVgY3F5A=
and get rid of these

2019-06-09 19:41 UTC, mellena1 commented on mbta/shapes.go
> +type GetShapeRequestConfig struct {
Move this one down to above getshape

2019-06-09 19:41 UTC, mellena1 commented on mbta/shapes.go
> +	Include []string `url:"include,comma,omitempty"`       // Can include choose to include route and stop.
```suggestion
	Include []ShapeInclude `url:"include,comma,omitempty"`       // Can include choose to include route and stop.
```

2019-06-09 19:41 UTC, mellena1 commented on mbta/shapes.go
> +func (s *ShapeService) GetAllShapes(config GetAllShapesRequestConfig) ([]*Shape, *http.Response, error) {
Change all of the config parameters to pointers because we decided to change them all to pointers at one point

2019-07-08 15:47 UTC, mellena1 approved these changes
LGTM

2019-07-08 15:47 UTC, merged